let content = {
    title: "Lygia et Aurelia",
    content: [
        "Aurélia  Platon (à droite) est  enseignante  primaire  au  sein  du Département  de  l’Instruction  Publique  à  Genève.  Après  avoir  travaillé quelques  années  en  tant  qu’animatrice  parascolaire  et  avoir réalisé  la Formation  pour  les Fonctions  d'Encadrement  des  Activités  du  Temps Libre (CEFOC | HETS), elle se forme à l’Université de Genève en Sciences de l’Éducation et complète ses études avec un Master Interdisciplinaire en Droits de l’Enfant.",
        "En parallèle, elle se forme à l’animation de dialogues philosophiques avec les enfants, jusqu’à devenir membre du comité de proPhilo (Genève) et de la commission “Communication et valorisation” de la Chaire UNESCO “Pratiques de la philosophie avec les enfants : une base éducative pour  le  dialogue  interculturel  et  la  transformation  sociale”  (Paris).  En 2019,  ces  deux  “casquettes” l’amènent à co - organiser les Rencontres Internationales sur les Nouvelles Pratiques Philosophiques se déroulant à l’Université de Genève.",
        "Au croisement de ses différents centres d’intérêt et compétences, elle se spécialise dans la question de la participation des enfants (en lien à l’article 12 de la Convention des Droits de l’Enfant) et engage une réflexion autour de la place et de l’importance qui peuvent être données aux pensées ainsi qu’à la parole des enfants dans le contexte scolaire.",
        "Depuis  2017,  elle  participe  également  en  tant  que  comédienne  à  divers  projets  théâtraux  portant  à chaque fois, au travers de ces derniers, des questionnements sur l’identité féminine. Elle est également improvisatrice  depuis  4  ans  (Impro  Suisse,  Fédération d’Improvisation  Genevoise)  et  enseigne l’improvisation théâtrale aux plus jeunes depuis 2019.",
        "Lygia Pavitt (à gauche) est fraîchement diplômée d’un Master de Psychologie sociale à l’Université de Genève, qu’elle a conclu avec un mémoire sur les effets néfastes du sexisme bienveillant sur l’aspiration au leadership chez les femmes. Mue par son envie grandissante de se battre contre les  inégalités  de genre, elle  s'est  tout  naturellement  orientée  vers  le Service Égalité de l'Université de Genève, afin d'y effectuer son stage de Master",
        "Fort de huit ans de pratique d'improvisation théâtrale, elle forme depuis trois  ans  de  nombreux·ses  comédien·ne·s via  les  activités  culturelles  de  l'UNIGE  et  la  Fédération d'Improvisation Genevoise (F!G). Lygia s’active particulièrement au sein du comité junior de la F!G, qui organise  le  championnat  genevois  junior  d’improvisation,  ainsi  que  du  comité  de  la  Laituge  (Ligue amateure  d’improvisation  universitaire  de  Genève).  De  par  ses  rôles  associatifs,  elle  apprend  les éléments logistiques propre à la gestion de spectacles.",
        "Sa formation en psychologie permet d’apporter un regard scientifique sur l’intervention et d’en mesurer l’impact concret.",
    ],
}

export default content
